plugins {
    id 'java-library'
}

group = 'org.mentalizr'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    maven { url = "https://raw.githubusercontent.com/arthurpicht/mvn-repo/main/releases"}
}

dependencies {
    implementation libs.m7r.persistenceMongo
    implementation libs.m7r.serviceObjects
    implementation libs.qos.logback
}
